\documentclass{article}
\usepackage{amsmath} %This allows me to use the align functionality.
                     %If you find yourself trying to replicate
                     %something you found online, ensure you're
                     %loading the necessary packages!
\usepackage{amsfonts}%Math font
\usepackage{graphicx}%For including graphics
\usepackage{hyperref}%For Hyperlinks
\usepackage[shortlabels]{enumitem}% For enumerated lists with labels specified
                                  % We had to run tlmgr_install("enumitem") in R
\hypersetup{colorlinks = true,citecolor=black} %set citations to have black (not green) color
\usepackage{natbib}        %For the bibliography
\setlength{\bibsep}{0pt plus 0.3ex}
\bibliographystyle{apalike}%For the bibliography
\usepackage[margin=0.50in]{geometry}
\usepackage{float}
\usepackage{multicol}

%fix for figures
\usepackage{caption}
\newenvironment{Figure}
  {\par\medskip\noindent\minipage{\linewidth}}
  {\endminipage\par\medskip}
\begin{document}

\vspace{-1in}
\title{Lab 05 -- MATH 240 -- Computational Statistics}

\author{
  Andrew Li \\
  Colgate University  \\
  Department of Mathematics  \\
  {\tt ali@colgate.edu}
}

\date{}

\maketitle

\begin{multicols}{2}
\begin{abstract}
This experiment seek to analyze how big of an influence did different music groups have on songs, specifically how much did the bands Manchester Orchestra, The Front Bottoms, and All Get Out affect the song ``Allentown." By using Essentia \citep{bogdanov2013essentia}, an open-source program for music analysis and synthesis, the musical components of 180 songs were isolated to be compared with the parts of ``Allentown." This method would be give more depth into the analysis and provide a better understanding of what elements are extracted from music. Through this process, the steps of data cleaning and summarization will be explored.  

\end{abstract}

\noindent \textbf{Keywords:} Cleaning data, extracting and automating data processing 

\section{Introduction}

Music plays such an important role in everyday lives, from creating social spaces, providing an outlet, and connecting people throughout the world. As a result, the works of different artists can be traced to find influence from older generations or their peers. The song ``Allentown" by Front Bottoms and Manchester Orchestra has influence from the two bands and All Get Out, so this lab seeks to explore what elements are similar and who overall has contributed the most to the creation of this song. There are many ways to conduct this comparison, but musical components was an objective way to analyze in pieces how similar the songs are. To do this, Essentia \citep{bogdanov2013essentia} is going to be used to collect data via music analysis. Since Essentia allows processing on individual tracks, it became neccesary to prepare a batch of json files using the tracks from all the artists. 



\section{Methods}
To replicate this experiment, it is important to make sure to download the jsonlite and stringr \texttt{R} packages. The music directory contained all 181 of the song tracks from the three bands, and we created a program that extracted all the provided .wav files (musical files) and processed them to create the batch file of executable command lines for the Essentia program to run. Using the \texttt{stringr} \citep{st} package for R , we were able to extract information from each wave file and organize each line by artist and album. Following that, we used the \texttt{jsonlite} \citep{js} package to create a sample program that can pull information from the json files that Essentia would return. This preliminary step showed how the larger scale data extraction will work. \\
\indent To get a full picture on which band plays the most influence, we took the data from the Essentia processed calls, drew additional features such as mood from Essentia models \citep{alonso2020tensorflow}, and analyzed thoughts and personality traits through a text analysis tool called LIWC. This was all compiled into one \texttt{csv} file to sort and organize all of our data before we initiated a feature-by-feature comparison to see what insights we can draw about the rise of the song ``Allentown." \\
\indent Using boxplots, a sample analysis was shown for the emotional element for ``Allentown" compared to the tracks from the three bands. 

Using the tidyverse package for \texttt{R} \citep{tidyverse}, it became easier to summerize and visualize our data because of the extensive functionality built into the package. Comparing individual values would have taken a large amount of space, lots of time, and difficulty to read, so to get a full analysis, we took all of the musical features, compared if the values of each feature from ``Allentown" are similar to  those from each artist, and graphed the proportion of songs that have similar traits in Figure \ref{plot3}. Using the \texttt{xtable} package \citep{xtable}, a sample of some of the analytical work is shown in Table \ref{table1} before. The total mark of 1.00 would have meant that musical features of the artist's songs were not identical, but all very similar in style. 



\section{Results}
Initially, it waas hard to determine what band had a greater influence on the song ``Allentown." By collecting analyzed musical elements and processed components, it becomes possible to see what parts of the song are similar to the works of Manchester Orchestra, All Get Out, or The Front Bottoms. The final product from the data collection and cleaning is presented inside the trainingdata.csv file while the musical components for ``Allentown" is separated inside the testingdata.csv to avoid conflicting overlap. 
  
When looking at just the emotional aspect of the songs by the three bands in Figure \ref{plot1}, the dashed line represents the value of the emotional aspect of ``Allentown," and comparing just this value would point to Manchester Orchestra as the main contributor since the song is within its IQR while being in the lower quartile for All Get Out and The Front Bottoms. However, when comparing the chords scale in Figure \ref{plot2}, more songs from The Front Bottoms share similar chords as ``Allentown," so instead, Figure \ref{plot3} showed the comparison for all traits . It can be determined that Manchester Orchestra has played the most influence on the creation of Allentown because it has a noticeable amount of similar traits in their music. While the songs were not exactly the same (1.00 being the maximum similarity), Manchester Orchestra's works is 10 percent greater than those of All Get Out and The Front Bottoms.


<<plot1, eval = FALSE, echo =FALSE, size='scriptsize', message=FALSE>>=
library(tidyverse)
trainingdata.csv <- read_csv("training.csv")
testingdata.csv <- read_csv("testing.csv")

#isolate out allentown
allentown <- filter(testingdata.csv, album == "Allentown")

# group together the data by artists
combined_data <- bind_rows(
  All.Get.Out <-
    filter(trainingdata.csv, artist == "All Get Out") %>% mutate(Artist = "AGO"),
  Manchester.Orchestra <-
    filter(trainingdata.csv,artist == "Manchester Orchestra") %>% mutate(Artist = "MO"),
  Front.Bottoms <-
    filter(trainingdata.csv,artist == "The Front Bottoms") %>%mutate(Artist = "TFB")
  )

ggplot(combined_data) +
  geom_boxplot(aes(x = emotion, y = Artist, fill = Artist)) +
  geom_vline(xintercept = allentown$emotion, size =1, linetype = "dashed") + 
  labs(
    x = "emotional values",
    y = "Artist"
  ) +
  theme_bw() +
  theme(legend.position = "none")+
  scale_x_continuous(limits = c(0, 7.5))+
  scale_fill_brewer(palette = "Set2")
@

\begin{figure}[H]
\begin{center}
<<echo=FALSE, warning=FALSE, message=FALSE, fig.dim=c(5,3.5)>>=
<<plot1>>
@
\caption{Emotional sound analysis \\ (names are shortened to MO, AGO, and TFB)}
\label{plot1} 
\end{center}
\end{figure}


<<plot2, eval = FALSE, echo =FALSE, size='scriptsize', message=FALSE>>=
library(tidyverse)
training.csv <- read_csv("data/essentia.data.csv") 

dat.chords.scale <- training.csv %>%
  group_by(artist) %>%
  summarise(total = n(), count = sum(grepl("major", chords_scale))) %>%
  mutate(proportion = count/total) 
# create a bar plot 
ggplot(data=dat.chords.scale)+
  geom_col(aes(x=artist, y = proportion, fill=artist),    
           position = position_dodge(.5)) + 
  geom_hline(yintercept = 0)+
  xlab("")+                        
  ylab("Chords scale proportion")+
  ylim(0,1)+                          
  theme_bw()+
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        )
@

\begin{figure}[H]
\begin{center}
<<echo=FALSE, warning=FALSE, message=FALSE, fig.dim=c(5,3.5)>>=
<<plot2>>
@
\caption{Songs similarity analysis based on chords scale }
\label{plot2} 
\end{center}
\end{figure}

<<plot3, eval = FALSE, echo =FALSE, size='scriptsize', message=FALSE>>=

#read processed data and pulled out all similarities
processed.data <- read_csv(file = "processed data.csv")
bar.data <- processed.data %>%
  group_by(artist) %>%
  summarise(proportion = length(which(description == "Within Range"))/ n())

ggplot(data=bar.data)+
  geom_col(aes(x=artist, y = proportion, fill=artist),    
           position = position_dodge(.5)) + 
  geom_hline(yintercept = 0)+
  xlab("")+                        
  ylab("Proportion of features within range")+
  ylim(0,1)+                          
  theme_bw()+
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        )
@

\begin{figure}[H]
\begin{center}
<<echo=FALSE, warning=FALSE, message=FALSE, fig.dim=c(5,3.5)>>=
<<plot3>>
@
\caption{Songs similarity analysis based on total features}
\label{plot3} 
\end{center}
\end{figure}


\section{Discussion}
  Given Figure \ref{plot1} and Figure \ref{plot2}, it can be seen how individual musical feature comparison gives an insufficient amount of information to determine which band had the greatest influence on the song ``Allentown." After extracting wav files and creating additional analyzing additional features from them through Essentia models and LIWC, the final cummulative processing of data cleaning formed Figure \ref{plot3} which shows how Manchester Orchestra contribued the most to the creation of the song. This type of analysis can be used to further determine the influence of other musicians on the works on any of these three bands or attribute similarities between different songs.




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Bibliography
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\vspace{2em}
\begin{tiny}
\bibliography{bib}
\end{tiny}
\end{multicols}
\newpage



\section{Appendix}

\begin{table}[H]
\centering
\begin{tabular}{rlrrrrlll}
  \hline
 & artist & minimum & LF & RF & maximum & out.of.range & unusual & description \\ 
  \hline
1 & All Get Out & -14.27 & -16.35 & -5.10 & -6.13 & FALSE & FALSE & Within Range \\ 
  2 & Manchester Orchestra & -24.34 & -20.22 & -5.66 & -6.26 & FALSE & FALSE & Within Range \\ 
  3 & The Front Bottoms & -11.03 & -9.65 & -6.81 & -5.71 & FALSE & TRUE & Unusual \\ 
  4 & All Get Out & 0.02 & 0.01 & 0.04 & 0.05 & FALSE & FALSE & Within Range \\ 
  5 & Manchester Orchestra & 0.01 & -0.00 & 0.04 & 0.05 & FALSE & FALSE & Within Range \\ 
  6 & The Front Bottoms & 0.02 & 0.02 & 0.05 & 0.05 & FALSE & FALSE & Within Range \\ 
  7 & All Get Out & 0.84 & 0.77 & 1.18 & 1.30 & FALSE & FALSE & Within Range \\ 
  8 & Manchester Orchestra & 0.78 & 0.65 & 1.21 & 1.40 & FALSE & FALSE & Within Range \\ 
  9 & The Front Bottoms & 0.91 & 0.86 & 1.24 & 1.33 & TRUE & FALSE & Out of Range \\ 
  10 & All Get Out & 84.91 & 95.29 & 149.76 & 162.92 & FALSE & FALSE & Within Range \\ 
  11 & Manchester Orchestra & 67.15 & 71.18 & 160.30 & 184.57 & FALSE & FALSE & Within Range \\ 
  12 & The Front Bottoms & 80.83 & 82.99 & 157.05 & 165.67 & FALSE & FALSE & Within Range \\ 
  13 & All Get Out & 163.50 & 134.57 & 261.03 & 377.87 & FALSE & FALSE & Within Range \\ 
  14 & Manchester Orchestra & 102.43 & 79.15 & 320.67 & 434.36 & FALSE & FALSE & Within Range \\ 
  15 & The Front Bottoms & 108.49 & 127.14 & 258.48 & 297.35 & FALSE & FALSE & Within Range \\ 
  16 & All Get Out & 0.04 & 0.02 & 0.08 & 0.08 & FALSE & FALSE & Within Range \\ 
  17 & Manchester Orchestra & 0.02 & 0.00 & 0.07 & 0.09 & FALSE & FALSE & Within Range \\ 
  18 & The Front Bottoms & 0.04 & 0.04 & 0.07 & 0.11 & TRUE & TRUE & Out of Range \\ 
  19 & All Get Out & 0.43 & 0.26 & 1.05 & 1.29 & FALSE & FALSE & Within Range \\ 
  20 & Manchester Orchestra & 0.42 & 0.11 & 1.07 & 1.35 & FALSE & FALSE & Within Range \\ 
  21 & The Front Bottoms & 0.52 & 0.38 & 0.99 & 1.36 & FALSE & FALSE & Within Range \\ 
  22 & All Get Out & 2620015.25 & 3162397.09 & 4788882.53 & 4758639.50 & TRUE & TRUE & Out of Range \\ 
  23 & Manchester Orchestra & 1937052.25 & 1668651.00 & 4817223.00 & 5845988.50 & FALSE & TRUE & Unusual \\ 
  24 & The Front Bottoms & 3510343.75 & 3538674.50 & 5508843.50 & 5888673.00 & FALSE & FALSE & Within Range \\ 
   
   \hline
\end{tabular} \caption{Sample data from musical analysis} \label{table1}
\end{table}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Appendix
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\end{document}